<div class="Dialog">
    <div class="Card Dialog-Content">
        <div class="Head">
            <h1>Paylaşım silinecek</h1>
        </div>
        <div class="Body">
            <p>'Başlık' isimli paylaşım silinecek, emin misiniz?</p>
        </div>
        <nav class="Dialog-Nav">
            <button class="Button Cancel">İptal</button>
            <button class="Button Danger Confirm">Sil</button>
        </nav>
    </div>
</div>