<section id="Login" style="background-image: url(./Assets/loginbg.jpg);">
    <main class="Card">
        <h1>Giriş yap</h1>

        <div class="Form">
            <label>
                <span>Kullanıcı adı</span>
                <input type="text" class="Input-Text" id="Username" autocomplete="off">
            </label>
            <label>
                <span>Parola</span>
                <input type="password" class="Input-Text" id="Password" autocomplete="off">
            </label>
            <span class="Message Danger Hide">Mesaj</span>
            <button class="Button" id="Log">Giriş yap</button>
        </div>
    </main>
</section>