<!--META-->
<title>Panel Template</title>
<link rel="shortcut icon" href="./Assets/pencil-alt.svg" type="image/svg">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<!--META END-->

<!--SOURCE-->
    <!--CSS-->
    <link rel="stylesheet" href="./CSS/style.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" crossorigin="anonymous">
    <link rel="stylesheet" href="./CSS/Quill.css">

    <!--JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" crossorigin="anonymous"></script>
    <script src="./JS/Quill/Quill.min.js"></script>
    <script src="./JS/Loader.js"></script>
    <script src="./JS/Main.js"></script>
    <script src="./JS/Editor.js"></script>
    <script src="./JS/Post.js"></script>
    <script src="./JS/Dialog.js"></script>
<!--SOURCE END-->