<!--META-->
<title>Panel Template</title>
<link rel="shortcut icon" href="./Assets/pencil-alt.svg" type="image/svg">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!--META END-->

<!--SOURCE-->
    <!--CSS-->
    <link rel="stylesheet" href="./CSS/style.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" crossorigin="anonymous">

    <!--JS-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" crossorigin="anonymous"></script>
    <script src="./JS/Login.js"></script>
<!--SOURCE END-->