<template id="CardTemplate">
    <article class="Post-Card">

    <div class="Head">
        <div class="Image-Wrap">
            <img class="Image">
        </div>
        <h4 class="Info">00 00 000</h4>
        <h1>Header</h1>
    </div>

    <div class="Body">
        <p>Content</p>
    </div>

    <nav class="Dialog-Nav">
        <button class="Button Danger Delete" onclick="">Sil</button>
        <button class="Button Edit">Düzenle</button>
    </nav>

    </article>
</template>