<section class="Overlay-Page" id="Editor">

<main>
    <div class="Image-Wrap">
        <img class="Image" id="EditorThumbnail">
        <input type="file" id="ImageFile" accept="image/jpeg, image/png">
        <input type="hidden" id="Base64Thumbnail">
    </div>

    <input type="text" class="Input-Text" id="Title" autocomplete="off" placeholder="Başlık...">
    <div id="Content"></div>

    <nav class="Dialog-Nav">
        <button class="Button Danger" id="EditorCancel">İptal</button>
        <button class="Button" id="DonePost">Paylaş</button>
    </nav>
</main>

</section>